#!/usr/bin/bash

PID=$$
trap ctrl_c SIGINT

function ctrl_c() {
	echo -e "\nСкрипт досрочно завершен пользователем."
	kill -SIGTERM $PID
}

echo $1
python parser.py "$1" && python analysis.py &&
	xelatex -output-dir=$HOME/Documents/data_science/hh_project/tmp report.tex
echo "Закончили скрипт."


