#!/usr/bin/bash

PID=$$
trap ctrl_c SIGINT

function ctrl_c() {
	echo -e "\nСкрипт досрочно завершен пользователем."
	kill -SIGTERM $PID
}

if [ $# -eq 0 ]
then
    echo "Ожидается наименование вакансии ... "
fi

if [ $# -eq 1 ]
then
    python parser.py "$1" && python analysis.py &&  xelatex -output-dir=$PWD/tmp report.tex
fi

if [ $# -eq 2 ]
then
    if [ $2 = "tech" ]
    then
        python parser.py "$1" && python analysis.py tech && xelatex -output-dir=$PWD/tmp report.tex
    fi
fi
echo "Закончили скрипт."

